on:
  pull_request:
    branches:
    - main
    - master
  push:
    branches:
    - main
    - master
    - develop
name: "Build & Release"

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17.x'
        cache: gradle

    - uses: subosito/flutter-action@v2
      with:
        #flutter-version: '2.10.5'
        channel: "stable"
        cache: true

    - run: flutter pub get
    - run: flutter build appbundle
    - run: flutter build apk

    #this is for web only build
    - run: flutter build web

    - uses: vimtor/action-zip@v1
      with:
        files: build/web
        dest: build/web.zip
        
    - name: Push to Releases
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "build/app/outputs/flutter-apk/*,build/app/outputs/bundle/release/*,build/web.zip"
        tag: v1.0.${{ github.run_number }}
        token: ${{ secrets.TOKEN }}


    - name: Push to Releases
    - uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        packageName: ${{ secrets.ANDROID_PACKAGE_NAME }}
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: internal
        status: completed
        token: ${{ secrets.TOKEN }}
